### ISSUE TITLE
Release to fix issue with the bundle

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy_gui_ipywidgets#12]
Would it be possible to do a quick release to make a new bundle more easily (#11)? Same for hyperspy_gui_traitsui.

See https://ci.appveyor.com/project/ericpre/hyperspy-bundle/builds/19658254/job/mce0r99xb177cctr

**Comment by francisco-dlp** [comment]
OK

**Comment by francisco-dlp** [comment]
Done, also for traitsui. However, they won't be in conda-forge until we release hspy 1.4.1.
