### ISSUE TITLE
Conda update

### ISSUE THREAD

**Issue by jlaehne** [hyperspy/hyperspy_gui_ipywidgets#38]
The automatic conda update seems to have failed, the package is still at 1.3.0:
https://anaconda.org/conda-forge/hyperspy-gui-ipywidgets

**Comment by jlaehne** [comment]
Or does it take a while until that is updated? I see the one for the traitsui was delayed as well.

**Comment by ericpre** [comment]
This is pending: https://github.com/conda-forge/hyperspy-gui-ipywidgets-feedstock/pull/14

**Comment by ericpre** [comment]
> Or does it take a while until that is updated? I see the one for the traitsui was delayed as well.

For the hyperspy_gui_traitsui, there was a failure in the pipeline and I had to restart it.

**Comment by ericpre** [comment]
Both packages are now available: https://anaconda.org/search?q=hyperspy
